#### Building Docker Image ####
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/sample:$SHORT_SHA', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/sample:${_IMAGE_TAG}', '.' ]

#### Pushing Docker Image ####
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: /bin/sh
  args: 
  - -c
  - |
    docker push europe-west4-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/sample:$SHORT_SHA
    docker push europe-west4-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/sample:${_IMAGE_TAG}

# This step generates the new manifest
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: /bin/sh
  secretEnv: ['GIT_ACCESS_TOKEN']
  args:
  - '-c'
  - |
    echo git clone https://syedislamuddin:$$GIT_ACCESS_TOKEN@github.com/syedislamuddin/gtserver-argocd.git -b ${_CD_BRANCH}
    git clone https://syedislamuddin:$$GIT_ACCESS_TOKEN@github.com/syedislamuddin/gtserver-argocd.git -b ${_CD_BRANCH}
    echo "Updating image tag version ..."
    cd gtserver-argocd
    sed "s/GOOGLE_CLOUD_PROJECT/$PROJECT_ID/g" deployment.yaml.tpl | \
    sed "s/COMMIT_SHA/${SHORT_SHA}/g" > deployment.yaml
    echo "Pushing changes to k8s manifest repo ..."
    git config --global user.name "syedislamuddin"
    git config --global user.email "islamuddinn@yahoo.com"
    git add -A
    git commit -m "[Cloud Builder] Updated image tag europe-west4.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/sample:$SHORT_SHA from commit ${COMMIT_SHA}"
    git push --no-thin https://syedislamuddin:$$GIT_ACCESS_TOKEN@github.com/syedislamuddin/gtserver-argocd.git ${_CD_BRANCH}
    
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_NUMBER/secrets/github-access-token/versions/latest
    env: 'GIT_ACCESS_TOKEN'

options:
  logging: CLOUD_LOGGING_ONLY
